endpoints:
  - name: "dugtrio-devnet12"
    executionUrl: "https://rpc.dencun-devnet-12.ethpandaops.io/"
    consensusUrl: "https://beacon.dencun-devnet-12.ethpandaops.io/"

web:
  server:
    host: "0.0.0.0"
    port: 8080
  frontend:
    enabled: true
    debug: true
    pprof: true

validatorNames:
  inventoryYaml: ""
  inventoryUrl: ""
  inventory:
    #"0-199": "lighthouse-geth-1"
    #"200-399": "teku-geth-1"

globalVars:
  validatorPairNames:
  #- "lighthouse-besu-.*"
  #- "lighthouse-erigon-.*"
  - "lighthouse-geth-.*"
  #- "lighthouse-nethermind-.*"
  #- "lodestar-besu-.*"
  #- "lodestar-erigon-.*"
  #- "lodestar-geth-.*"
  #- "lodestar-nethermind-.*"
  #- "nimbus-besu-.*"
  #- "nimbus-erigon-.*"
  #- "nimbus-geth-.*"
  #- "nimbus-nethermind-.*"
  #- "teku-besu-.*"
  #- "teku-erigon-.*"
  - "teku-geth-.*"
  #- "teku-nethermind-.*"

tests:

  # Every client combo proposes block
- name: "Every client combo proposes block"
  timeout: 48h
  tasks:
  - name: check_clients_are_healthy
    title: "Check if at least one client is ready"
    timeout: 5m
    config:
      minClientCount: 1
  - name: run_task_matrix
    title: "Check block proposals from all client pairs"
    configVars:
      matrixValues: "validatorPairNames"
    config:
      runConcurrent: true
      matrixVar: "validatorPairName"
      task:
        name: check_consensus_block_proposals
        title: "Wait for block proposal from ${validatorPairName}"
        configVars:
          validatorNamePattern: "validatorPairName"

  # Every cl client proposes a block with withdrawal messages
- name: "Every cl client proposes a block with withdrawal messages"
  timeout: 48h
  tasks:
  - name: check_clients_are_healthy
    title: "Check if at least one client is ready"
    timeout: 5m
    config:
      minClientCount: 1
  - name: run_tasks_concurrent
    title: "Generate BLS Changes & Track inclusion"
    config:
      succeedTaskCount: 1
      tasks:
      - name: generate_bls_changes
        title: "Generate BLS changes"
        config:
          mnemonic: "giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
          limitPerSlot: 1
          indexCount: 400
          targetAddress: 0x14627ea0e2B27b817DbfF94c3dA383bB73F8C30b
      - name: run_task_matrix
        title: "Check BLS inclusion with all client pairs"
        configVars:
          matrixValues: "validatorPairNames"
        config:
          runConcurrent: true
          matrixVar: "validatorPairName"
          task:
            name: check_consensus_block_proposals
            title: "Wait for block proposal with BLS changes from ${validatorPairName}"
            configVars:
              validatorNamePattern: "validatorPairName"
            config:
              minBlsChangeCount: 1

  # Every client pair proposed block with deposits
- name: "Every client pair proposed block with deposits"
  timeout: 48h
  tasks:
  - name: check_clients_are_healthy
    title: "Check if at least one client is ready"
    timeout: 5m
    config:
      minClientCount: 1

  - name: run_tasks_concurrent
    title: "Generate deposits & Track inclusion"
    config:
      tasks:
      - name: generate_deposits
        title: "Generate deposits"
        config:
          mnemonic: "trial jeans seat abstract runway cupboard please elevator club file arrow lounge crash sun thumb clock duty priority key fence funny trick diary album"
          limitTotal: 100
          limitPerSlot: 5
          walletPrivkey: "94eb3102993b41ec55c241060f47daa0f6372e2e3ad7e91612ae36c364042e44"
          depositContract: "0x00000000219ab540356cBB839Cbe05303d7705Fa"

      - name: run_task_matrix
        title: "Check deposit inclusion with all client pairs"
        configVars:
          matrixValues: "validatorPairNames"
        config:
          runConcurrent: true
          matrixVar: "validatorPairName"
          task:
            name: check_consensus_block_proposals
            title: "Wait for block proposal with deposits from ${validatorPairName}"
            configVars:
              validatorNamePattern: "validatorPairName"
            config:
              minDepositCount: 1

  # Every client pair proposed block with exits
- name: "Every client pair proposed block with exits"
  timeout: 48h
  tasks:
  - name: check_clients_are_healthy
    title: "Check if at least one client is ready"
    timeout: 5m
    config:
      minClientCount: 1

  - name: run_tasks_concurrent
    title: "Generate exits & Track inclusion"
    config:
      succeedTaskCount: 1
      tasks:
      - name: generate_exits
        title: "Generate 50 voluntary exits"
        config:
          mnemonic: "trial jeans seat abstract runway cupboard please elevator club file arrow lounge crash sun thumb clock duty priority key fence funny trick diary album"
          limitTotal: 50
          limitPerSlot: 1
          indexCount: 200

      - name: run_task_matrix
        title: "Check voluntary exit inclusion with all client pairs"
        configVars:
          matrixValues: "validatorPairNames"
        config:
          runConcurrent: true
          matrixVar: "validatorPairName"
          task:
            name: check_consensus_block_proposals
            title: "Wait for block proposal with deposits from ${validatorPairName}"
            configVars:
              validatorNamePattern: "validatorPairName"
            config:
              minExitCount: 1
