
# final stage
FROM debian:stable-slim
WORKDIR /app
RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  jq \
  git \
  curl \
  make \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN update-ca-certificates
COPY bin/* /app
EXPOSE 8080
ENTRYPOINT ["./assertoor"]
CMD []
