
# final stage
FROM debian:stable-slim
RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  jq \
  git \
  curl \
  make \
  sudo \
  gnupg \
  python3 \
  python3-pip \
  python3-dev \
  && curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
  && apt-get install -y --no-install-recommends nodejs \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && update-ca-certificates
RUN groupadd -g 10001 assertoor && useradd -m -u 10001 -g assertoor assertoor
RUN echo "assertoor ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/assertoor
WORKDIR /app
COPY bin/* /app/
RUN chown -R assertoor:assertoor /app
USER assertoor
EXPOSE 8080
ENTRYPOINT ["./assertoor"]
CMD []
