# syntax=docker/dockerfile:1
FROM golang:1.21 AS builder
WORKDIR /src
COPY go.sum go.mod ./
RUN go mod download
COPY main.go Makefile ./
ADD .git ./.git
ADD cmd ./cmd
ADD pkg ./pkg
RUN make build

FROM debian:stable-slim
RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  jq \
  git \
  curl \
  make \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
COPY --from=builder /src/bin/assertoor /assertoor
RUN mkdir /workspace
WORKDIR /workspace
ENTRYPOINT ["/assertoor"]