participants:
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: lighthouse
    cl_image: sigp/lighthouse:latest
    count: 3
network_params:
  seconds_per_slot: 12
additional_services:
  - assertoor
snooper_enabled: true
assertoor_params:
  run_stability_check: false
  run_block_proposal_check: false
