// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/clients": {
            "get": {
                "description": "Returns the list of configured consensus and execution layer clients with their current status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Get list of configured clients",
                "operationId": "getClients",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetClientsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard_config": {
            "get": {
                "description": "Returns the persisted dashboard layout (JSON blob).\nPublic read; mutations are auth-gated via PUT.\nReturns 204 when no config has been saved yet — the\nUI falls back to a built-in default in that case.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get the active dashboard config",
                "operationId": "getDashboardConfig",
                "responses": {
                    "200": {
                        "description": "Dashboard config JSON",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "204": {
                        "description": "No config persisted yet"
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Auth-required. Persists the supplied JSON blob as the\nactive dashboard layout. The body is treated as\nopaque — the server only checks that it parses as\nvalid JSON; semantic validation lives in the client.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Replace the active dashboard config",
                "operationId": "putDashboardConfig",
                "responses": {
                    "200": {
                        "description": "Saved",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/global_variables": {
            "get": {
                "description": "Returns the names of all configured global variables. Values are not included as they may contain sensitive data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Get global variable names",
                "operationId": "getGlobalVariables",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetGlobalVariablesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/logs/{since}": {
            "get": {
                "description": "Returns application-level logs from the coordinator. Protected endpoint - requires authentication unless auth is disabled.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Get application logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Log index to start from (0 for all)",
                        "name": "since",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetLogsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/network_status": {
            "get": {
                "description": "Aggregated snapshot of the chain (head, finalized,\njustified, current slot/epoch) and the orchestration\nstate (client readiness counts, test queue depth).\nPowers the dashboard ` + "`" + `network_status` + "`" + ` tile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Network"
                ],
                "summary": "Get a network-wide status snapshot",
                "operationId": "getNetworkStatus",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.NetworkStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/playbook_library": {
            "get": {
                "description": "Returns the index of playbooks available from the configured upstream\n(default: ethpandaops/assertoor master). The response includes the\nresolved base URL used to fetch individual playbooks and the folder\nmetadata harvested from ` + "`" + `_header.yaml` + "`" + ` files.\nThe index is cached server-side; a stale copy is served if a refresh fails.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PlaybookLibrary"
                ],
                "summary": "Get the published playbook library index",
                "operationId": "getPlaybookLibrary",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/playbooklibrary.IndexResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Library disabled",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/playbook_library/check": {
            "get": {
                "description": "Fetches the remote YAML for the given library file and compares it\nagainst any locally registered test with the same id. The response\ntells the caller whether to register fresh (absent), skip registration\nand run the existing test (same), or warn before overwriting (different).\nRequires authentication because the response includes local YAML which\nmay contain sensitive configuration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PlaybookLibrary"
                ],
                "summary": "Compare a library playbook against the locally-registered copy",
                "operationId": "getPlaybookLibraryCheck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Library file path (e.g. stable/stability-check.yaml)",
                        "name": "file",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetPlaybookLibraryCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "404": {
                        "description": "Library disabled or file not in index",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/task_descriptor/{name}": {
            "get": {
                "description": "Returns a single task descriptor by name with its JSON schema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get a specific task descriptor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/tasks.TaskDescriptorAPI"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/task_descriptors": {
            "get": {
                "description": "Returns a list of all available task descriptors with their JSON schemas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get all task descriptors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/tasks.TaskDescriptorAPI"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/test/{testId}": {
            "get": {
                "description": "Returns the test definition with given ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Get test definition by test ID",
                "operationId": "getTest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test definition to get details for",
                        "name": "testId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetTestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test/{testId}/latest_result": {
            "get": {
                "description": "Walks recent runs of the test (newest first) and returns\nthe first $ASSERTOOR_TEST_RESULT markdown blob found.\nReturns 200 with metadata in headers (X-Run-Id, X-Run-Status,\nX-Run-Start-Time) and the markdown as the body.\nWhen ?meta=1 is set, returns a JSON envelope instead\n(handy for tile fetchers that want one round-trip).",
                "produces": [
                    "text/markdown",
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Get the latest run-level result markdown for a test",
                "operationId": "getTestLatestResult",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "testId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set to 1 to receive a JSON envelope",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Markdown body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "204": {
                        "description": "No result available across recent runs"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "404": {
                        "description": "Test not found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test/{testId}/next_run": {
            "get": {
                "description": "Walks each cron expression on the test's schedule\nand returns the next firing time per expression plus\nthe overall earliest one. Empty when the test has no\ncron schedule.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Get the next planned cron firings for a test",
                "operationId": "getTestNextRun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "testId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetTestNextRunResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Test not found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test/{testId}/schedule": {
            "put": {
                "description": "Auth-required. Replaces the schedule (cron + startup\n+ skipQueue) for a registered test. Cron expressions\nare validated up-front; invalid input rejects the\nwhole request without changing state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Update a test's run schedule",
                "operationId": "putTestSchedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "testId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New schedule",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.PutTestScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Saved",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "404": {
                        "description": "Test not found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test/{testId}/yaml": {
            "get": {
                "description": "Returns the full YAML source for a test definition. For API-registered tests, returns the stored YAML. For external tests referenced by file/URL, loads and returns the content from the original source. Requires authentication as YAML may contain sensitive configuration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Get test YAML source by test ID",
                "operationId": "getTestYaml",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test definition to get YAML for",
                        "name": "testId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetTestYamlResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_queue": {
            "get": {
                "description": "Returns the pending test queue in execution order\nplus any currently running tests at the head. Used\nby the StartTestModal's QueuePicker to let users\nslot a new run at a chosen position.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get the current test runner queue",
                "operationId": "getTestQueue",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetTestQueueResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/test_run/{runId}": {
            "get": {
                "description": "Returns the run details with given ID. Includes a summary and a list of task with limited details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get test run by run ID",
                "operationId": "getTestRun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test run to get details for",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetTestRunResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_run/{runId}/cancel": {
            "post": {
                "description": "Returns the test/run id \u0026 status of the cancelled test.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Cancel test run by test ID",
                "operationId": "postTestRunCancel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test run to cancel",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Test cancellation options",
                        "name": "cancelOptions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.PostTestRunCancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.PostTestRunCancelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_run/{runId}/details": {
            "get": {
                "description": "Returns the run details with given ID. Includes a summary and a list of task with all details (incl. logs \u0026 task configurations)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get detailed test run by run ID",
                "operationId": "getTestRunDetails",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test run to get details for",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetTestRunDetailsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_run/{runId}/result": {
            "get": {
                "description": "Returns the markdown blob that tasks have collectively\nwritten to $ASSERTOOR_TEST_RESULT during the run, if any.\nRendered by the UI as the run's prominent Result panel.",
                "produces": [
                    "text/markdown",
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get the run-level result markdown",
                "operationId": "getTestRunResult",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test run",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Markdown body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "204": {
                        "description": "No result set for this run"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "404": {
                        "description": "Test run not found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_run/{runId}/status": {
            "get": {
                "description": "Returns the run status with given ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get test run status by run ID",
                "operationId": "getTestRunStatus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test run to get the status for",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_run/{runId}/task/{taskIndex}/details": {
            "get": {
                "description": "Returns the task details with given run ID and task index. Includes full log, configuration and result variables (unless security trimmed).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get detailed task of a given test run",
                "operationId": "getTestRunTaskDetails",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test run",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Index of the task to get details for",
                        "name": "taskIndex",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetTestRunDetailedTask"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_run/{runId}/task/{taskIndex}/result/{resultType}/{fileId}": {
            "get": {
                "description": "Returns a specific result file from a task. Requires authentication as results may contain sensitive data.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get task result file",
                "operationId": "getTaskResult",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the test run",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type of file to return (summary, result, ...)",
                        "name": "resultType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Index or name of the result file",
                        "name": "fileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_runs": {
            "get": {
                "description": "Returns a list of all test runs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Get list of test runs",
                "operationId": "getTestRuns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Return test runs for this test ID only",
                        "name": "test_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web_api.GetTestRunsResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_runs/delete": {
            "post": {
                "description": "Deletes test runs",
                "consumes": [
                    "application/json",
                    "application/yaml"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Delete test runs",
                "operationId": "postTestRunsDelete",
                "parameters": [
                    {
                        "description": "Test configuration (json or yaml)",
                        "name": "testConfig",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.PostTestRunsDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.PostTestRunsDeleteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/test_runs/schedule": {
            "post": {
                "description": "Returns the test \u0026 run id of the scheduled test execution.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestRun"
                ],
                "summary": "Schedule new test run by test ID",
                "operationId": "postTestRunsSchedule",
                "parameters": [
                    {
                        "description": "Rest run options",
                        "name": "runOptions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.PostTestRunsScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.PostTestRunsScheduleResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tests": {
            "get": {
                "description": "Returns the list of test definitions. These test definitions can be used to create new test runs and are supplied via the assertoor configuration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Get list of test definitions",
                "operationId": "getTests",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web_api.GetTestsResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tests/delete": {
            "post": {
                "description": "Deletes tests",
                "consumes": [
                    "application/json",
                    "application/yaml"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Delete tests",
                "operationId": "postTestsDelete",
                "parameters": [
                    {
                        "description": "Test configuration (json or yaml)",
                        "name": "testConfig",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.PostTestsDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.PostTestsDeleteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tests/register": {
            "post": {
                "description": "Returns the test id and name of the added test.",
                "consumes": [
                    "application/json",
                    "application/yaml"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Register new test via yaml configuration",
                "operationId": "postTestsRegister",
                "parameters": [
                    {
                        "description": "Test configuration (json or yaml)",
                        "name": "testConfig",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.PostTestsRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.PostTestsRegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tests/register_external": {
            "post": {
                "description": "Returns the test id and name of the added test.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Register new test via external test configuration",
                "operationId": "postTestsRegisterExternal",
                "parameters": [
                    {
                        "description": "Test configuration (json or yaml)",
                        "name": "externalTestConfig",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.PostTestsRegisterExternalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.PostTestsRegisterExternalResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Failure",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/web_api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/version": {
            "get": {
                "description": "Returns the build version (commit hash) and release of the running Assertoor binary.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Get build version information",
                "operationId": "getVersion",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web_api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web_api.GetVersionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helper.RawMessage": {
            "type": "object"
        },
        "playbooklibrary.FolderEntry": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "playbooklibrary.IndexResponse": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "folders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/playbooklibrary.FolderEntry"
                    }
                },
                "generated": {
                    "type": "string"
                },
                "index_url": {
                    "type": "string"
                },
                "playbooks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/playbooklibrary.PlaybookEntry"
                    }
                }
            }
        },
        "playbooklibrary.PlaybookEntry": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "file": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timeout": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "tasks.TaskDescriptorAPI": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "configSchema": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.TaskOutputDefinition"
                    }
                }
            }
        },
        "types.TaskOutputDefinition": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.TestSchedule": {
            "type": "object",
            "properties": {
                "cron": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "skipQueue": {
                    "type": "boolean"
                },
                "startup": {
                    "type": "boolean"
                }
            }
        },
        "types.TestStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "success",
                "failure",
                "skipped",
                "aborted"
            ],
            "x-enum-varnames": [
                "TestStatusPending",
                "TestStatusRunning",
                "TestStatusSuccess",
                "TestStatusFailure",
                "TestStatusSkipped",
                "TestStatusAborted"
            ]
        },
        "web_api.ClientResponse": {
            "type": "object",
            "properties": {
                "cl_error": {
                    "type": "string"
                },
                "cl_head_root": {
                    "type": "string"
                },
                "cl_head_slot": {
                    "type": "integer"
                },
                "cl_ready": {
                    "type": "boolean"
                },
                "cl_refresh": {
                    "type": "string"
                },
                "cl_status": {
                    "type": "string"
                },
                "cl_type": {
                    "type": "integer"
                },
                "cl_version": {
                    "type": "string"
                },
                "el_error": {
                    "type": "string"
                },
                "el_head_hash": {
                    "type": "string"
                },
                "el_head_number": {
                    "type": "integer"
                },
                "el_ready": {
                    "type": "boolean"
                },
                "el_refresh": {
                    "type": "string"
                },
                "el_status": {
                    "type": "string"
                },
                "el_type": {
                    "type": "integer"
                },
                "el_version": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "web_api.GetClientsResponse": {
            "type": "object",
            "properties": {
                "client_count": {
                    "type": "integer"
                },
                "clients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.ClientResponse"
                    }
                }
            }
        },
        "web_api.GetGlobalVariablesResponse": {
            "type": "object",
            "properties": {
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "web_api.GetLogsResponse": {
            "type": "object",
            "properties": {
                "log": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.LogEntry"
                    }
                }
            }
        },
        "web_api.GetPlaybookLibraryCheckResponse": {
            "type": "object",
            "properties": {
                "local_name": {
                    "type": "string"
                },
                "local_test_id": {
                    "type": "string"
                },
                "local_yaml": {
                    "type": "string"
                },
                "remote_id": {
                    "type": "string"
                },
                "remote_name": {
                    "type": "string"
                },
                "remote_url": {
                    "type": "string"
                },
                "remote_yaml": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestNextRunEntry": {
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string"
                },
                "next": {
                    "type": "integer"
                }
            }
        },
        "web_api.GetTestNextRunEntryEarliest": {
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string"
                },
                "next": {
                    "type": "integer"
                }
            }
        },
        "web_api.GetTestNextRunResponse": {
            "type": "object",
            "properties": {
                "earliest": {
                    "$ref": "#/definitions/web_api.GetTestNextRunEntryEarliest"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.GetTestNextRunEntry"
                    }
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestQueueEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/types.TestStatus"
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestQueueResponse": {
            "type": "object",
            "properties": {
                "queue": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.GetTestQueueEntry"
                    }
                }
            }
        },
        "web_api.GetTestResponse": {
            "type": "object",
            "properties": {
                "basePath": {
                    "type": "string"
                },
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "configVars": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "$ref": "#/definitions/types.TestSchedule"
                },
                "source": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timeout": {
                    "type": "integer"
                },
                "vars": {
                    "description": "Config with global vars merged in",
                    "type": "object",
                    "additionalProperties": {}
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestRunDetailedTask": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "config_yaml": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "log": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.GetTestRunDetailedTaskLog"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parent_index": {
                    "type": "integer"
                },
                "progress": {
                    "type": "number"
                },
                "progress_message": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "result_error": {
                    "type": "string"
                },
                "result_files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.GetTestRunTaskResult"
                    }
                },
                "result_yaml": {
                    "type": "string"
                },
                "run_concurrent": {
                    "type": "boolean"
                },
                "runtime": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "started": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "stop_time": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestRunDetailedTaskLog": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "datalen": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestRunDetailsResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/types.TestStatus"
                },
                "stop_time": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.GetTestRunDetailedTask"
                    }
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestRunResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/types.TestStatus"
                },
                "stop_time": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.GetTestRunTask"
                    }
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestRunTask": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "index": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parent_index": {
                    "type": "integer"
                },
                "result": {
                    "type": "string"
                },
                "result_error": {
                    "type": "string"
                },
                "result_files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web_api.GetTestRunTaskResult"
                    }
                },
                "run_concurrent": {
                    "type": "boolean"
                },
                "runtime": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "started": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "stop_time": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestRunTaskResult": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestRunsResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/types.TestStatus"
                },
                "stop_time": {
                    "type": "integer"
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestYamlResponse": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "yaml": {
                    "type": "string"
                }
            }
        },
        "web_api.GetTestsResponse": {
            "type": "object",
            "properties": {
                "basePath": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "web_api.GetVersionResponse": {
            "type": "object",
            "properties": {
                "release": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "web_api.LogEntry": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "datalen": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "tidx": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "web_api.NetworkStatusResponse": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "cl_ready_count": {
                    "type": "integer"
                },
                "client_count": {
                    "type": "integer"
                },
                "current_epoch": {
                    "type": "integer"
                },
                "current_slot": {
                    "type": "integer"
                },
                "el_head_hash": {
                    "type": "string"
                },
                "el_head_number": {
                    "type": "integer"
                },
                "el_ready_count": {
                    "type": "integer"
                },
                "finalized_epoch": {
                    "type": "integer"
                },
                "finalized_root": {
                    "type": "string"
                },
                "genesis_time": {
                    "type": "integer"
                },
                "head_root": {
                    "type": "string"
                },
                "head_slot": {
                    "type": "integer"
                },
                "justified_epoch": {
                    "type": "integer"
                },
                "justified_root": {
                    "type": "string"
                },
                "network_name": {
                    "type": "string"
                },
                "slot_duration_ms": {
                    "type": "integer"
                },
                "slots_per_epoch": {
                    "type": "integer"
                },
                "tests_queued": {
                    "type": "integer"
                },
                "tests_running": {
                    "type": "integer"
                }
            }
        },
        "web_api.PostTestRunCancelRequest": {
            "type": "object",
            "properties": {
                "skip_cleanup": {
                    "type": "boolean"
                }
            }
        },
        "web_api.PostTestRunCancelResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.PostTestRunsDeleteRequest": {
            "type": "object",
            "properties": {
                "test_runs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "web_api.PostTestRunsDeleteResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "web_api.PostTestRunsScheduleRequest": {
            "type": "object",
            "properties": {
                "allow_duplicate": {
                    "type": "boolean"
                },
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "queue": {
                    "description": "Queue is the modern (v2) way of expressing where the new test\nshould slot relative to the runner's pending queue. When unset\nthe request falls back to SkipQueue. See ScheduleQueueOption.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/web_api.ScheduleQueueOption"
                        }
                    ]
                },
                "skip_queue": {
                    "description": "SkipQueue is the legacy boolean that drove \"off-queue parallel\nexecution\". Kept for backward compatibility — when Queue is\nsupplied it wins; otherwise we fall through to this field.\n\nDeprecated: use Queue with mode=\"immediate\".",
                    "type": "boolean"
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.PostTestRunsScheduleResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "integer"
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.PostTestsDeleteRequest": {
            "type": "object",
            "properties": {
                "tests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "web_api.PostTestsDeleteResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "web_api.PostTestsRegisterExternalRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "configVars": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "file": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "$ref": "#/definitions/types.TestSchedule"
                },
                "timeout": {
                    "type": "integer"
                }
            }
        },
        "web_api.PostTestsRegisterExternalResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.PostTestsRegisterRequest": {
            "type": "object",
            "properties": {
                "cleanupTasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helper.RawMessage"
                    }
                },
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "configVars": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "$ref": "#/definitions/types.TestSchedule"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helper.RawMessage"
                    }
                },
                "timeout": {
                    "type": "string"
                }
            }
        },
        "web_api.PostTestsRegisterResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "test_id": {
                    "type": "string"
                }
            }
        },
        "web_api.PutTestScheduleRequest": {
            "type": "object",
            "properties": {
                "schedule": {
                    "description": "Schedule is the new schedule. May be null to clear.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.TestSchedule"
                        }
                    ]
                }
            }
        },
        "web_api.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "web_api.ScheduleQueueMode": {
            "type": "string",
            "enum": [
                "immediate",
                "end",
                "after"
            ],
            "x-enum-varnames": [
                "ScheduleQueueModeImmediate",
                "ScheduleQueueModeEnd",
                "ScheduleQueueModeAfter"
            ]
        },
        "web_api.ScheduleQueueOption": {
            "type": "object",
            "properties": {
                "after_run_id": {
                    "description": "AfterRunID is honoured only when Mode == \"after\". The new test\nis placed immediately after that run in the pending queue. If\nthe referenced run is no longer queued the request silently\nfalls back to \"append to end\".",
                    "type": "integer"
                },
                "mode": {
                    "$ref": "#/definitions/web_api.ScheduleQueueMode"
                }
            }
        }
    },
    "tags": [
        {
            "description": "All endpoints related to test definitions",
            "name": "Test"
        },
        {
            "description": "All endpoints related to test runs",
            "name": "TestRun"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Assertoor API Documentation",
	Description:      "API for querying information about Assertoor tests",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
