id: pectra-all
name: "All pectra tests"
timeout: 2h
config:
  #walletPrivkey: ""
tasks:
  - name: check_consensus_slot_range
    title: "Wait for slot >= 34"
    timeout: 2h
    config:
      minSlotNumber: 34
  - name: run_external_tasks
    title: "Generate BLS changes for validator 0-30"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/bls-changes.yaml
      testConfig:
        validatorCount: 30
  
  # EIP-6110
  - name: check_consensus_slot_range
    title: "Wait for slot >= 38"
    timeout: 2h
    config:
      minSlotNumber: 38
  - name: run_external_tasks
    title: "Generate massive deposit with 0x02 creds"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/massive-deposit-0x02.yaml

  # EIP-2935
  - name: check_consensus_slot_range
    title: "Wait for slot >= 42"
    timeout: 2h
    config:
      minSlotNumber: 42
  - name: run_external_tasks
    title: "Deploy and test blockhash contract"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/blockhash-test.yaml
  
  # EIP-7002
  - name: check_consensus_slot_range
    title: "Wait for slot >= 46"
    timeout: 2h
    config:
      minSlotNumber: 46
  - name: run_external_tasks
    title: "Generate voluntary exits for validator 0-10"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/voluntary-exits.yaml
      testConfig:
        validatorCount: 10
  - name: check_consensus_slot_range
    title: "Wait for slot >= 50"
    timeout: 2h
    config:
      minSlotNumber: 50
  - name: run_external_tasks
    title: "EL-triggered exit test for validator 20"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/el-triggered-exit.yaml
      testConfig:
        validatorIndex: 20

  # EIP-7251
  - name: check_consensus_slot_range
    title: "Wait for slot >= 54"
    timeout: 2h
    config:
      minSlotNumber: 54
  - name: run_external_tasks
    title: "Withdrawal credential change for validator 25 to 0x02 creds via self consolidation"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/el-triggered-consolidation.yaml
      testConfig:
        sourceValidatorIndex: 25
        targetValidatorIndex: 25
  - name: check_consensus_slot_range
    title: "Wait for slot >= 58"
    timeout: 2h
    config:
      minSlotNumber: 58
  - name: run_external_tasks
    title: "Generate EL-triggered consolidation for validator 21"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/el-triggered-consolidation.yaml
      testConfig:
        sourceValidatorIndex: 21
        targetValidatorIndex: 25

  # run long-running test
  - name: check_consensus_slot_range
    title: "Wait for slot >= 64"
    timeout: 2h
    config:
      minSlotNumber: 64
  - name: run_external_tasks
    title: "Run EIP7002-all test"
    timeout: 4h
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/eip7002-all.yaml
      testConfig:
        useExistingValidators: true
        validatorStartIndex: 30
  - name: run_external_tasks
    title: "Run EIP7251-all test"
    timeout: 4h
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/eip7251-all.yaml
      testConfig:
        useExistingValidators: true
        validatorStartIndex: 60

  # Final check
  - name: run_external_tasks
    title: "Final check"
    timeout: 60m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/block-proposal-check.yaml
