
id: fillup-all-el-queues
name: "Fillup all EL request queues"
timeout: 1h
config:
  walletPrivkey: ""
  requestCount: 1000  # number of requests to send
  walletCount:  10 # number of wallets to send from
  requestFeeAmount: 10000000000000000  # 0.01 ETH
  throughputPerWallet: 20
  maxPendingPerWallet: 40
  walletSeed: ""
tasks:
- name: check_clients_are_healthy
  title: "Check if at least one client is ready"
  timeout: 5m
  config:
    minClientCount: 1

# wait for electra activation
- name: get_consensus_specs
  id: get_specs
  title: "Get consensus chain specs"
- name: check_consensus_slot_range
  title: "Wait for electra activation"
  timeout: 1h
  configVars:
    minEpochNumber: "tasks.get_specs.outputs.specs.ELECTRA_FORK_EPOCH"

# fillup all EL request queues (deposit, withdrawal, consolidation)
- name: run_tasks_concurrent
  title: "Fillup all EL request queues"
  config:
    tasks:
    - name: run_external_tasks
      title: "Fillup deposit queue with ${{requestCount}} deposits"
      config:
        testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/fillup-deposit-queue.yaml
      configVars:
        testConfig: "| { \"depositCount\": .requestCount, \"depositMaxIndex\": .walletCount, \"throughputPerIndex\": .throughputPerWallet, \"maxPendingPerIndex\": .maxPendingPerWallet, \"walletSeed\": .walletSeed }"
    - name: run_external_tasks
      title: "Fillup withdrawal request queue with ${{requestCount}} withdrawal requests"
      config:
        testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/fillup-withdrawal-queue.yaml
      configVars:
        testConfig: "| { \"withdrawalCount\": .requestCount, \"withdrawalMaxIndex\": .walletCount, \"withdrawalTxFee\": .requestFeeAmount, \"throughputPerIndex\": .throughputPerWallet, \"maxPendingPerIndex\": .maxPendingPerWallet, \"walletSeed\": .walletSeed }"
    - name: run_external_tasks
      title: "Fillup consolidation request queue with ${{requestCount}} consolidation requests"
      config:
        testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/fillup-consolidation-queue.yaml
      configVars:
        testConfig: "| { \"consolidationCount\": .requestCount, \"consolidationMaxIndex\": .walletCount, \"consolidationTxFee\": .requestFeeAmount, \"throughputPerIndex\": .throughputPerWallet, \"maxPendingPerIndex\": .maxPendingPerWallet, \"walletSeed\": .walletSeed }"
