
name: Check PR

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_source:
    name: "Run code checks"
    uses: ./.github/workflows/_shared-check.yaml

